spring:
  application:
    name: todo


  datasource:
    url: jdbc:mysql://localhost:3306/codesch?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true

    # db response name
    username: root

    # db response password
    password: jang1109!




kakao:
  client_id: b23af313ad89940e19a6df68ec84a94c
  redirect_uri: https://to-do-list-client-two.vercel.app/kakao/callback/



