spring:
  application:
    name: todo

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:postgresql://192.168.2.37:5432/todolistdb
    username: todolist
    password: todolistpwd

  kakao:
    key:
      client_id: b23af313ad89940e19a6df68ec84a94c
    redirect_uri: https://to-do-list-client-two.vercel.app/kakao/callback/

custom:
  jwt:
    secretKey: 392FC4B8E169C7471238435EA67E1
